export const TOKENS = {
  PG_POOL: 'PG_POOL',
  UNIT_OF_WORK: 'UNIT_OF_WORK',
  WALLET_REPOSITORY: 'WALLET_REPOSITORY',
  WAGER_TRANSACTION_REPOSITORY: 'WAGER_TRANSACTION_REPOSITORY',
  LEDGER_REPOSITORY: 'LEDGER_REPOSITORY',
  INBOX_REPOSITORY: 'INBOX_REPOSITORY',
  OUTBOX_REPOSITORY: 'OUTBOX_REPOSITORY',
  CLOCK: 'CLOCK',
  ID_GENERATOR: 'ID_GENERATOR',
} as const;
